/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line.thrift;


public enum GroupAttribute implements org.apache.thrift.TEnum {
  NAME(1),
  PICTURE_STATUS(2),
  ALL(255);

  private final int value;

  private GroupAttribute(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static GroupAttribute findByValue(int value) { 
    switch (value) {
      case 1:
        return NAME;
      case 2:
        return PICTURE_STATUS;
      case 255:
        return ALL;
      default:
        return null;
    }
  }
}
