/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package line.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MIDType implements org.apache.thrift.TEnum {
  USER(0),
  ROOM(1),
  GROUP(2);

  private final int value;

  private MIDType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MIDType findByValue(int value) { 
    switch (value) {
      case 0:
        return USER;
      case 1:
        return ROOM;
      case 2:
        return GROUP;
      default:
        return null;
    }
  }
}
