/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linecorp.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum NotificationStatus implements org.apache.thrift.TEnum {
  NOTIFICATION_ITEM_EXIST(1),
  TIMELINE_ITEM_EXIST(2),
  NOTE_GROUP_NEW_ITEM_EXIST(4),
  TIMELINE_BUDDYGROUP_CHANGED(8),
  NOTE_ONE_TO_ONE_NEW_ITEM_EXIST(16),
  ALBUM_ITEM_EXIST(32),
  TIMELINE_ITEM_DELETED(64);

  private final int value;

  private NotificationStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NotificationStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return NOTIFICATION_ITEM_EXIST;
      case 2:
        return TIMELINE_ITEM_EXIST;
      case 4:
        return NOTE_GROUP_NEW_ITEM_EXIST;
      case 8:
        return TIMELINE_BUDDYGROUP_CHANGED;
      case 16:
        return NOTE_ONE_TO_ONE_NEW_ITEM_EXIST;
      case 32:
        return ALBUM_ITEM_EXIST;
      case 64:
        return TIMELINE_ITEM_DELETED;
      default:
        return null;
    }
  }
}
